version: '2'
services:
  db:
    container_name: postgresql
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
    networks:
      - postgres
    ports:
      - "5432:5432"
    volumes:
        - ./postgresql:/var/lib/postgresql/data
    restart: always

  odoo14:
    container_name: odoo14
    image: odoo:14
    depends_on:
      - db
    ports:
      - "9999:8069"
    networks:
      - postgres
    tty: true
    command: -- --dev=reload
    volumes:
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
    restart: always

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin
      - PGADMIN_DEFAULT_PASSWORD=pgadmin
    depends_on:
      - db
    ports:
      - "5080:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge
